### ISSUE TITLE
`chunksOfLeft` is not typesafe

### ISSUE THREAD

**Issue by Fresheyeball** [elm-community/list-split#3]
`chunksOfLeft 0` causes a stack overflow. Considering returning `[[]]` or `Nothing`.

**Comment by jonboiser** [comment]
Thanks for pointing this out. Having it return `[[]]` seems to make more sense to me.

In [the Haskell version of this](http://hackage.haskell.org/package/split-0.1.1/docs/Data-List-Split.html#v:splitEvery), `chunk 0 xs` would return an infinite `[[],[],[],...]`, which is what this code seems to do. But Elm doesn't do lazy evaluation (I believe), hence the stack overflow.

Just curious, does something like `take 4 <| chunksOfLeft 0 xs` still work? I kind of doubt it, but want to confirm, since the whole 'no laziness' thing was something I heard on a podcast, but haven't actually checked out.

Would you like to submit a PR?

**Comment by Fresheyeball** [comment]
#4
